import { EMPLOYEE_SHIFT_STATUSES } from "@/configs/entities.config.ts"

import mongoose, { Document, InferSchemaType, Model } from "mongoose"

/**
 * EmployeeShift Entity
 *
 * Represents a daily generated shift record for a specific employee.
 * This is the operational record that tracks what shift an employee is SUPPOSED
 * to work on a specific day.
 *
 * - Usually auto-generated by the system based on `ShiftSchedule` and `HolidayCalendar`.
 * - Can be overridden manually by HR (marked via `isOverride: true`).
 * - Serves as the basis for evaluating actual attendance (Check-In/Out) via `AttendanceRecord`.
 */
const employeeShiftSchema = new mongoose.Schema(
  {
    employeeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Employee",
      required: true,
    },

    shiftId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "WorkingShift",
      required: true,
    },

    assignedDate: {
      type: Date,
      required: true,
      set: (value: Date) => {
        const date = new Date(value)
        date.setHours(0, 0, 0, 0)
        return date
      },
    },

    scheduleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ShiftSchedule",
      default: null,
    },

    status: {
      type: String,
      enum: EMPLOYEE_SHIFT_STATUSES,
      default: "scheduled",
      required: true,
    },

    isOverride: {
      type: Boolean,
      default: false,
    },

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Employee",
      required: true,
    },
  },
  { timestamps: true },
)

// Compound unique: một nhân viên chỉ được assign 1 ca mỗi ngày
employeeShiftSchema.index({ employeeId: 1, assignedDate: 1 }, { unique: true })
employeeShiftSchema.index({ shiftId: 1, assignedDate: 1 })
employeeShiftSchema.index({ status: 1, assignedDate: 1 })
employeeShiftSchema.index({ scheduleId: 1 })

const EmployeeShift = mongoose.model("EmployeeShift", employeeShiftSchema)

export default EmployeeShift
export type EmployeeShiftType = InferSchemaType<typeof employeeShiftSchema>
export type EmployeeShiftDocument = Document & EmployeeShiftType
export type EmployeeShiftModel = Model<EmployeeShiftDocument>
