export const PERMISSION_CODE = {
  PERMISSION_READ: "permission.read",
  PERMISSION_CREATE: "permission.create",
  PERMISSION_UPDATE: "permission.update",
  PERMISSION_DELETE: "permission.delete",
  ROLE_PERMISSION_READ: "role.permission.read",
  ROLE_PERMISSION_UPDATE: "role.permission.update",
  EMPLOYEE_ROLE_READ: "employee.role.read",
  EMPLOYEE_ROLE_UPDATE: "employee.role.update",
  PROJECT_UPDATE: "project.update",
  APPLICATION_READ: "application.read",
  APPLICATION_APPROVE: "application.approve",
  ATTENDANCE_WEEKLY_SCHEDULE_READ: "attendance.weekly_schedule.read",
  PAYROLL_SALARY_CONFIG_READ: "payroll.salary_config.read",
} as const

export const PERMISSION_CODES = [
  PERMISSION_CODE.PERMISSION_READ,
  PERMISSION_CODE.PERMISSION_CREATE,
  PERMISSION_CODE.PERMISSION_UPDATE,
  PERMISSION_CODE.PERMISSION_DELETE,
  PERMISSION_CODE.ROLE_PERMISSION_READ,
  PERMISSION_CODE.ROLE_PERMISSION_UPDATE,
  PERMISSION_CODE.EMPLOYEE_ROLE_READ,
  PERMISSION_CODE.EMPLOYEE_ROLE_UPDATE,
  PERMISSION_CODE.PROJECT_UPDATE,
  PERMISSION_CODE.APPLICATION_READ,
  PERMISSION_CODE.APPLICATION_APPROVE,
  PERMISSION_CODE.ATTENDANCE_WEEKLY_SCHEDULE_READ,
  PERMISSION_CODE.PAYROLL_SALARY_CONFIG_READ,
] as const

export type PermissionCode = (typeof PERMISSION_CODES)[number]
