/**
 * Represents a single API endpoint in the system's route manifest.
 */
export interface RouteManifestEntry {
  name: string
  description?: string
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "ALL"
  path: string
  authRequired: boolean
  permissions: string[] | null
}

/**
 * Centralized Route Manifest containing all API endpoints.
 * This is the Single Source of Truth for system routes and permissions.
 */
export const ROUTE_MANIFEST: RouteManifestEntry[] = [
  // Applications
  {
    name: "Danh sách Đơn từ",
    description: "Lấy danh sách Đơn từ trong hệ thống",
    method: "GET",
    path: "/api/applications",
    authRequired: true,
    permissions: ["application.read"],
  },
  {
    name: "Tạo mới Đơn từ",
    description: "Thêm một Đơn từ mới vào hệ thống",
    method: "POST",
    path: "/api/applications",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Chi tiết Đơn từ",
    description: "Xem thông tin chi tiết của một Đơn từ",
    method: "GET",
    path: "/api/applications/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật /:id/approve",
    description: "API endpoint cho Đơn từ",
    method: "PATCH",
    path: "/api/applications/:id/approve",
    authRequired: true,
    permissions: ["application.approve"],
  },
  {
    name: "Cập nhật /:id/cancel",
    description: "API endpoint cho Đơn từ",
    method: "PATCH",
    path: "/api/applications/:id/cancel",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật /:id/reject",
    description: "API endpoint cho Đơn từ",
    method: "PATCH",
    path: "/api/applications/:id/reject",
    authRequired: true,
    permissions: ["application.approve"],
  },
  {
    name: "Lấy /employee/:employeeId",
    description: "API endpoint cho Đơn từ",
    method: "GET",
    path: "/api/applications/employee/:employeeId",
    authRequired: true,
    permissions: ["application.read"],
  },
  {
    name: "Lấy /me",
    description: "API endpoint cho Đơn từ",
    method: "GET",
    path: "/api/applications/me",
    authRequired: false,
    permissions: null,
  },

  // Approvals
  {
    name: "Danh sách Phê duyệt",
    description: "Lấy danh sách Phê duyệt trong hệ thống",
    method: "GET",
    path: "/api/approvals",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật /:category/:id",
    description: "API endpoint cho Phê duyệt",
    method: "PATCH",
    path: "/api/approvals/:category/:id",
    authRequired: false,
    permissions: null,
  },

  // Attendance
  {
    name: "Danh sách Điểm danh",
    description: "Lấy danh sách Điểm danh trong hệ thống",
    method: "GET",
    path: "/api/attendance",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /check-in",
    description: "API endpoint cho Điểm danh",
    method: "POST",
    path: "/api/attendance/check-in",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /check-out",
    description: "API endpoint cho Điểm danh",
    method: "POST",
    path: "/api/attendance/check-out",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Lấy /export",
    description: "API endpoint cho Điểm danh",
    method: "GET",
    path: "/api/attendance/export",
    authRequired: true,
    permissions: ["attendance.export"],
  },

  // Part-time availability
  {
    name: "Lịch rảnh PT — của tôi",
    description: "Nhân viên PT xem lịch rảnh tuần hiện tại",
    method: "GET",
    path: "/api/part-time-availabilities/mine",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Lịch rảnh PT — gửi/cập nhật",
    description: "Nhân viên PT gửi hoặc cập nhật lịch rảnh tuần",
    method: "PUT",
    path: "/api/part-time-availabilities/mine",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Lịch rảnh PT — danh sách tuần",
    description: "Admin xem tất cả lịch rảnh PT trong tuần",
    method: "GET",
    path: "/api/part-time-availabilities",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Lịch rảnh PT — theo nhân viên",
    description: "Admin xem lịch rảnh PT của một nhân viên",
    method: "GET",
    path: "/api/part-time-availabilities/employee/:employeeId",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Lịch rảnh PT — xếp ca",
    description: "Admin xếp ca từ lịch rảnh đã gửi",
    method: "POST",
    path: "/api/part-time-availabilities/:id/assign-shifts",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Thực hiện /scan",
    description: "API endpoint cho Điểm danh",
    method: "POST",
    path: "/api/attendance/scan",
    authRequired: false,
    permissions: null,
  },

  // Audit
  {
    name: "Lấy /audit",
    description: "API endpoint cho Audit",
    method: "GET",
    path: "/api/audit",
    authRequired: true,
    permissions: ["audit.read"],
  },
  {
    name: "Lấy /audit/:id",
    description: "API endpoint cho Audit",
    method: "GET",
    path: "/api/audit/:id",
    authRequired: true,
    permissions: ["audit.read"],
  },
  {
    name: "Lấy /employees/:id/audit",
    description: "API endpoint cho Audit",
    method: "GET",
    path: "/api/audit/employees/:id/audit",
    authRequired: true,
    permissions: ["audit.read"],
  },
  {
    name: "Lấy /roles/:id/audit",
    description: "API endpoint cho Audit",
    method: "GET",
    path: "/api/audit/roles/:id/audit",
    authRequired: true,
    permissions: ["audit.read"],
  },

  // Authentication
  {
    name: "Lấy /activity-logs",
    description: "API endpoint cho Xác thực",
    method: "GET",
    path: "/api/auth/activity-logs",
    authRequired: true,
    permissions: ["security.read"],
  },
  {
    name: "Lấy /activity-logs/:id",
    description: "API endpoint cho Xác thực",
    method: "GET",
    path: "/api/auth/activity-logs/:id",
    authRequired: true,
    permissions: ["security.read"],
  },
  {
    name: "Thực hiện /change-password",
    description: "API endpoint cho Xác thực",
    method: "POST",
    path: "/api/auth/change-password",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Thực hiện /forgot-password",
    description: "API endpoint cho Xác thực",
    method: "POST",
    path: "/api/auth/forgot-password",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Đăng nhập",
    description: "Xác thực người dùng bằng username/password",
    method: "POST",
    path: "/api/auth/login",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Đăng xuất",
    description: "Xóa token và phiên làm việc",
    method: "POST",
    path: "/api/auth/logout",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Lấy thông tin cá nhân",
    description: "Lấy thông tin user hiện tại",
    method: "GET",
    path: "/api/auth/me",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Lấy /me/activity-logs",
    description: "API endpoint cho Xác thực",
    method: "GET",
    path: "/api/auth/me/activity-logs",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Lấy /me/activity-logs/:id",
    description: "API endpoint cho Xác thực",
    method: "GET",
    path: "/api/auth/me/activity-logs/:id",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Thực hiện /refresh",
    description: "API endpoint cho Xác thực",
    method: "POST",
    path: "/api/auth/refresh",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /reset-password",
    description: "API endpoint cho Xác thực",
    method: "POST",
    path: "/api/auth/reset-password",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /validate-reset-token",
    description: "API endpoint cho Xác thực",
    method: "POST",
    path: "/api/auth/validate-reset-token",
    authRequired: false,
    permissions: null,
  },

  // Custom Queries
  {
    name: "Danh sách Truy vấn tùy chỉnh",
    description: "Lấy danh sách Truy vấn tùy chỉnh trong hệ thống",
    method: "GET",
    path: "/api/custom-queries",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Truy vấn tùy chỉnh",
    description: "Thêm một Truy vấn tùy chỉnh mới vào hệ thống",
    method: "POST",
    path: "/api/custom-queries",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Xóa Truy vấn tùy chỉnh",
    description: "Xóa Truy vấn tùy chỉnh khỏi hệ thống",
    method: "DELETE",
    path: "/api/custom-queries/:id",
    authRequired: false,
    permissions: null,
  },

  // Debug
  {
    name: "Lấy /route-manifest",
    description: "API endpoint cho Debug",
    method: "GET",
    path: "/api/debug/route-manifest",
    authRequired: true,
    permissions: ["role.read"],
  },

  // Employee Salary Config
  {
    name: "Lấy /:id/salary-config",
    description: "API endpoint cho Cấu hình lương nhân viên",
    method: "GET",
    path: "/api/employees/:id/salary-config",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /:id/salary-config",
    description: "API endpoint cho Cấu hình lương nhân viên",
    method: "POST",
    path: "/api/employees/:id/salary-config",
    authRequired: true,
    permissions: ["payroll.create"],
  },
  {
    name: "Lấy /:id/salary-config/history",
    description: "API endpoint cho Cấu hình lương nhân viên",
    method: "GET",
    path: "/api/employees/:id/salary-config/history",
    authRequired: false,
    permissions: null,
  },

  // Employees
  {
    name: "Danh sách Nhân viên",
    description: "Lấy danh sách Nhân viên trong hệ thống",
    method: "GET",
    path: "/api/employees",
    authRequired: true,
    permissions: ["employee.read"],
  },
  {
    name: "Tạo mới Nhân viên",
    description: "Thêm một Nhân viên mới vào hệ thống",
    method: "POST",
    path: "/api/employees",
    authRequired: true,
    permissions: ["employee.create"],
  },
  {
    name: "Chi tiết Nhân viên",
    description: "Xem thông tin chi tiết của một Nhân viên",
    method: "GET",
    path: "/api/employees/:id",
    authRequired: true,
    permissions: ["employee.read"],
  },
  {
    name: "Cập nhật Nhân viên",
    description: "Chỉnh sửa thông tin Nhân viên hiện có",
    method: "PATCH",
    path: "/api/employees/:id",
    authRequired: true,
    permissions: ["employee.update"],
  },
  {
    name: "Xóa Nhân viên",
    description: "Xóa Nhân viên khỏi hệ thống",
    method: "DELETE",
    path: "/api/employees/:id",
    authRequired: true,
    permissions: ["employee.delete"],
  },
  {
    name: "Cập nhật /:id/status",
    description: "API endpoint cho Nhân viên",
    method: "PATCH",
    path: "/api/employees/:id/status",
    authRequired: true,
    permissions: ["employee.update"],
  },
  {
    name: "Lấy /approvers",
    description: "API endpoint cho Nhân viên",
    method: "GET",
    path: "/api/employees/approvers",
    authRequired: false,
    permissions: null,
  },

  // Holidays
  {
    name: "Danh sách Ngày nghỉ lễ",
    description: "Lấy danh sách Ngày nghỉ lễ trong hệ thống",
    method: "GET",
    path: "/api/holidays",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Ngày nghỉ lễ",
    description: "Thêm một Ngày nghỉ lễ mới vào hệ thống",
    method: "POST",
    path: "/api/holidays",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Cập nhật Ngày nghỉ lễ",
    description: "Chỉnh sửa thông tin Ngày nghỉ lễ hiện có",
    method: "PATCH",
    path: "/api/holidays/:id",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Xóa Ngày nghỉ lễ",
    description: "Xóa Ngày nghỉ lễ khỏi hệ thống",
    method: "DELETE",
    path: "/api/holidays/:id",
    authRequired: true,
    permissions: ["attendance.delete"],
  },
  {
    name: "Lấy /check",
    description: "API endpoint cho Ngày nghỉ lễ",
    method: "GET",
    path: "/api/holidays/check",
    authRequired: false,
    permissions: null,
  },

  // Payrolls
  {
    name: "Danh sách Bảng lương",
    description: "Lấy danh sách Bảng lương trong hệ thống",
    method: "GET",
    path: "/api/payrolls",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Chi tiết Bảng lương",
    description: "Xem thông tin chi tiết của một Bảng lương",
    method: "GET",
    path: "/api/payrolls/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /:id/approve",
    description: "API endpoint cho Bảng lương",
    method: "POST",
    path: "/api/payrolls/:id/approve",
    authRequired: true,
    permissions: ["payroll.approve"],
  },
  {
    name: "Lấy /:id/payslips/:empId",
    description: "API endpoint cho Bảng lương",
    method: "GET",
    path: "/api/payrolls/:id/payslips/:empId",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /:id/reject",
    description: "API endpoint cho Bảng lương",
    method: "POST",
    path: "/api/payrolls/:id/reject",
    authRequired: true,
    permissions: ["payroll.approve"],
  },
  {
    name: "Lấy /employee/:empId/payslips",
    description: "API endpoint cho Bảng lương",
    method: "GET",
    path: "/api/payrolls/employee/:empId/payslips",
    authRequired: true,
    permissions: ["payroll.read"],
  },
  {
    name: "Thực hiện /generate",
    description: "API endpoint cho Bảng lương",
    method: "POST",
    path: "/api/payrolls/generate",
    authRequired: true,
    permissions: ["payroll.create"],
  },
  {
    name: "Lấy /my/payslips",
    description: "API endpoint cho Bảng lương",
    method: "GET",
    path: "/api/payrolls/my/payslips",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Lấy /settings",
    description: "API endpoint cho Bảng lương",
    method: "GET",
    path: "/api/payrolls/settings",
    authRequired: true,
    permissions: ["payroll.update"],
  },
  {
    name: "Cập nhật /settings",
    description: "API endpoint cho Bảng lương",
    method: "PUT",
    path: "/api/payrolls/settings",
    authRequired: true,
    permissions: ["payroll.update"],
  },

  // Payslip Templates
  {
    name: "Danh sách Mẫu phiếu lương",
    description: "Lấy danh sách Mẫu phiếu lương trong hệ thống",
    method: "GET",
    path: "/api/payslip-templates",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Mẫu phiếu lương",
    description: "Thêm một Mẫu phiếu lương mới vào hệ thống",
    method: "POST",
    path: "/api/payslip-templates",
    authRequired: true,
    permissions: ["payroll.create"],
  },
  {
    name: "Cập nhật Mẫu phiếu lương",
    description: "Chỉnh sửa thông tin Mẫu phiếu lương hiện có",
    method: "PUT",
    path: "/api/payslip-templates/:id",
    authRequired: true,
    permissions: ["payroll.update"],
  },
  {
    name: "Xóa Mẫu phiếu lương",
    description: "Xóa Mẫu phiếu lương khỏi hệ thống",
    method: "DELETE",
    path: "/api/payslip-templates/:id",
    authRequired: true,
    permissions: ["payroll.delete"],
  },

  // Permissions
  {
    name: "Danh sách Quyền hạn",
    description: "Lấy danh sách Quyền hạn trong hệ thống",
    method: "GET",
    path: "/api/permissions",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Tạo mới Quyền hạn",
    description: "Thêm một Quyền hạn mới vào hệ thống",
    method: "POST",
    path: "/api/permissions",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Chi tiết Quyền hạn",
    description: "Xem thông tin chi tiết của một Quyền hạn",
    method: "GET",
    path: "/api/permissions/:id",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Cập nhật Quyền hạn",
    description: "Chỉnh sửa thông tin Quyền hạn hiện có",
    method: "PUT",
    path: "/api/permissions/:id",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Xóa Quyền hạn",
    description: "Xóa Quyền hạn khỏi hệ thống",
    method: "DELETE",
    path: "/api/permissions/:id",
    authRequired: true,
    permissions: null,
  },

  // Profile
  {
    name: "Lấy /me",
    description: "API endpoint cho Hồ sơ cá nhân",
    method: "GET",
    path: "/api/profile/me",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Cập nhật /me",
    description: "API endpoint cho Hồ sơ cá nhân",
    method: "PATCH",
    path: "/api/profile/me",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Thực hiện /me/avatar",
    description: "API endpoint cho Hồ sơ cá nhân",
    method: "POST",
    path: "/api/profile/me/avatar",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Thực hiện /me/change-password",
    description: "API endpoint cho Hồ sơ cá nhân",
    method: "POST",
    path: "/api/profile/me/change-password",
    authRequired: true,
    permissions: null,
  },
  {
    name: "Cập nhật /me/personal-employee-link",
    description: "API endpoint cho Hồ sơ cá nhân",
    method: "PATCH",
    path: "/api/profile/me/personal-employee-link",
    authRequired: true,
    permissions: null,
  },

  // Projects
  {
    name: "Danh sách Dự án",
    description: "Lấy danh sách Dự án trong hệ thống",
    method: "GET",
    path: "/api/projects",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Dự án",
    description: "Thêm một Dự án mới vào hệ thống",
    method: "POST",
    path: "/api/projects",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Chi tiết Dự án",
    description: "Xem thông tin chi tiết của một Dự án",
    method: "GET",
    path: "/api/projects/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật Dự án",
    description: "Chỉnh sửa thông tin Dự án hiện có",
    method: "PATCH",
    path: "/api/projects/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Xóa Dự án",
    description: "Xóa Dự án khỏi hệ thống",
    method: "DELETE",
    path: "/api/projects/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Lấy /:id/gantt",
    description: "API endpoint cho Dự án",
    method: "GET",
    path: "/api/projects/:id/gantt",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Lấy /:id/members",
    description: "API endpoint cho Dự án",
    method: "GET",
    path: "/api/projects/:id/members",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /:id/members",
    description: "API endpoint cho Dự án",
    method: "POST",
    path: "/api/projects/:id/members",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật /:id/members/:employeeId",
    description: "API endpoint cho Dự án",
    method: "PATCH",
    path: "/api/projects/:id/members/:employeeId",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Xóa /:id/members/:employeeId",
    description: "API endpoint cho Dự án",
    method: "DELETE",
    path: "/api/projects/:id/members/:employeeId",
    authRequired: false,
    permissions: null,
  },

  // Roles
  {
    name: "Danh sách Vai trò (Role)",
    description: "Lấy danh sách Vai trò (Role) trong hệ thống",
    method: "GET",
    path: "/api/roles",
    authRequired: true,
    permissions: ["role.read"],
  },
  {
    name: "Tạo mới Vai trò (Role)",
    description: "Thêm một Vai trò (Role) mới vào hệ thống",
    method: "POST",
    path: "/api/roles",
    authRequired: true,
    permissions: ["role.create"],
  },
  {
    name: "Chi tiết Vai trò (Role)",
    description: "Xem thông tin chi tiết của một Vai trò (Role)",
    method: "GET",
    path: "/api/roles/:id",
    authRequired: true,
    permissions: ["role.read"],
  },
  {
    name: "Cập nhật Vai trò (Role)",
    description: "Chỉnh sửa thông tin Vai trò (Role) hiện có",
    method: "PUT",
    path: "/api/roles/:id",
    authRequired: true,
    permissions: ["role.update"],
  },
  {
    name: "Xóa Vai trò (Role)",
    description: "Xóa Vai trò (Role) khỏi hệ thống",
    method: "DELETE",
    path: "/api/roles/:id",
    authRequired: true,
    permissions: ["role.delete"],
  },

  // Salary Components
  {
    name: "Danh sách Thành phần lương",
    description: "Lấy danh sách Thành phần lương trong hệ thống",
    method: "GET",
    path: "/api/salary-components",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Thành phần lương",
    description: "Thêm một Thành phần lương mới vào hệ thống",
    method: "POST",
    path: "/api/salary-components",
    authRequired: true,
    permissions: ["payroll.create"],
  },
  {
    name: "Cập nhật Thành phần lương",
    description: "Chỉnh sửa thông tin Thành phần lương hiện có",
    method: "PUT",
    path: "/api/salary-components/:id",
    authRequired: true,
    permissions: ["payroll.update"],
  },
  {
    name: "Xóa Thành phần lương",
    description: "Xóa Thành phần lương khỏi hệ thống",
    method: "DELETE",
    path: "/api/salary-components/:id",
    authRequired: true,
    permissions: ["payroll.delete"],
  },
  {
    name: "Thực hiện /validate",
    description: "API endpoint cho Thành phần lương",
    method: "POST",
    path: "/api/salary-components/validate",
    authRequired: true,
    permissions: ["payroll.create"],
  },

  // Salary Variables
  {
    name: "Danh sách Biến lương",
    description: "Lấy danh sách Biến lương trong hệ thống",
    method: "GET",
    path: "/api/salary-variables",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Biến lương",
    description: "Thêm một Biến lương mới vào hệ thống",
    method: "POST",
    path: "/api/salary-variables",
    authRequired: true,
    permissions: ["payroll.create"],
  },
  {
    name: "Chi tiết Biến lương",
    description: "Xem thông tin chi tiết của một Biến lương",
    method: "GET",
    path: "/api/salary-variables/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật Biến lương",
    description: "Chỉnh sửa thông tin Biến lương hiện có",
    method: "PUT",
    path: "/api/salary-variables/:id",
    authRequired: true,
    permissions: ["payroll.update"],
  },
  {
    name: "Xóa Biến lương",
    description: "Xóa Biến lương khỏi hệ thống",
    method: "DELETE",
    path: "/api/salary-variables/:id",
    authRequired: true,
    permissions: ["payroll.delete"],
  },

  // Schedules
  {
    name: "Thực hiện /assign",
    description: "API endpoint cho Lịch làm việc",
    method: "POST",
    path: "/api/schedules/assign",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Lấy /employee/:employeeId",
    description: "API endpoint cho Lịch làm việc",
    method: "GET",
    path: "/api/schedules/employee/:employeeId",
    authRequired: true,
    permissions: ["attendance.read"],
  },
  {
    name: "Lấy /employee/:employeeId/all",
    description: "API endpoint cho Lịch làm việc",
    method: "GET",
    path: "/api/schedules/employee/:employeeId/all",
    authRequired: true,
    permissions: ["attendance.read"],
  },
  {
    name: "Thực hiện /generate",
    description: "API endpoint cho Lịch làm việc",
    method: "POST",
    path: "/api/schedules/generate",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Thực hiện /generate/preview",
    description: "API endpoint cho Lịch làm việc",
    method: "POST",
    path: "/api/schedules/generate/preview",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Lấy /my",
    description: "API endpoint cho Lịch làm việc",
    method: "GET",
    path: "/api/schedules/my",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Lấy /my/all",
    description: "API endpoint cho Lịch làm việc",
    method: "GET",
    path: "/api/schedules/my/all",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /override",
    description: "API endpoint cho Lịch làm việc",
    method: "POST",
    path: "/api/schedules/override",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Lấy /settings",
    description: "API endpoint cho Lịch làm việc",
    method: "GET",
    path: "/api/schedules/settings",
    authRequired: true,
    permissions: ["attendance.read"],
  },
  {
    name: "Cập nhật /settings",
    description: "API endpoint cho Lịch làm việc",
    method: "PUT",
    path: "/api/schedules/settings",
    authRequired: true,
    permissions: ["attendance.update"],
  },

  // Security
  {
    name: "Lấy /dashboard",
    description: "API endpoint cho Bảo mật",
    method: "GET",
    path: "/api/security/dashboard",
    authRequired: true,
    permissions: ["security.read"],
  },
  {
    name: "Lấy /locked-accounts",
    description: "API endpoint cho Bảo mật",
    method: "GET",
    path: "/api/security/locked-accounts",
    authRequired: true,
    permissions: ["security.read"],
  },
  {
    name: "Cập nhật /unlock/:employeeId",
    description: "API endpoint cho Bảo mật",
    method: "PATCH",
    path: "/api/security/unlock/:employeeId",
    authRequired: true,
    permissions: ["security.update"],
  },

  // Shift Change Requests
  {
    name: "Tạo mới Yêu cầu đổi ca",
    description: "Thêm một Yêu cầu đổi ca mới vào hệ thống",
    method: "POST",
    path: "/api/shift-change-requests",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Lấy /mine",
    description: "API endpoint cho Yêu cầu đổi ca",
    method: "GET",
    path: "/api/shift-change-requests/mine",
    authRequired: false,
    permissions: null,
  },

  // Shifts
  {
    name: "Danh sách Ca làm việc",
    description: "Lấy danh sách Ca làm việc trong hệ thống",
    method: "GET",
    path: "/api/shifts",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Ca làm việc",
    description: "Thêm một Ca làm việc mới vào hệ thống",
    method: "POST",
    path: "/api/shifts",
    authRequired: true,
    permissions: ["attendance.create"],
  },
  {
    name: "Chi tiết Ca làm việc",
    description: "Xem thông tin chi tiết của một Ca làm việc",
    method: "GET",
    path: "/api/shifts/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật Ca làm việc",
    description: "Chỉnh sửa thông tin Ca làm việc hiện có",
    method: "PATCH",
    path: "/api/shifts/:id",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Xóa Ca làm việc",
    description: "Xóa Ca làm việc khỏi hệ thống",
    method: "DELETE",
    path: "/api/shifts/:id",
    authRequired: true,
    permissions: ["attendance.delete"],
  },

  // Spent Times
  {
    name: "Danh sách Thời gian làm việc",
    description: "Lấy danh sách Thời gian làm việc trong hệ thống",
    method: "GET",
    path: "/api/spent-times",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Thời gian làm việc",
    description: "Thêm một Thời gian làm việc mới vào hệ thống",
    method: "POST",
    path: "/api/spent-times",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Chi tiết Thời gian làm việc",
    description: "Xem thông tin chi tiết của một Thời gian làm việc",
    method: "GET",
    path: "/api/spent-times/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật Thời gian làm việc",
    description: "Chỉnh sửa thông tin Thời gian làm việc hiện có",
    method: "PATCH",
    path: "/api/spent-times/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Xóa Thời gian làm việc",
    description: "Xóa Thời gian làm việc khỏi hệ thống",
    method: "DELETE",
    path: "/api/spent-times/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /:id/approve",
    description: "API endpoint cho Thời gian làm việc",
    method: "POST",
    path: "/api/spent-times/:id/approve",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Thực hiện /:id/reject",
    description: "API endpoint cho Thời gian làm việc",
    method: "POST",
    path: "/api/spent-times/:id/reject",
    authRequired: false,
    permissions: null,
  },

  // Tasks
  {
    name: "Danh sách Công việc",
    description: "Lấy danh sách Công việc trong hệ thống",
    method: "GET",
    path: "/api/tasks",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Công việc",
    description: "Thêm một Công việc mới vào hệ thống",
    method: "POST",
    path: "/api/tasks",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Chi tiết Công việc",
    description: "Xem thông tin chi tiết của một Công việc",
    method: "GET",
    path: "/api/tasks/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật Công việc",
    description: "Chỉnh sửa thông tin Công việc hiện có",
    method: "PATCH",
    path: "/api/tasks/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Xóa Công việc",
    description: "Xóa Công việc khỏi hệ thống",
    method: "DELETE",
    path: "/api/tasks/:id",
    authRequired: false,
    permissions: null,
  },

  // Weekly Schedule Templates
  {
    name: "Danh sách Mẫu lịch làm việc tuần",
    description: "Lấy danh sách Mẫu lịch làm việc tuần trong hệ thống",
    method: "GET",
    path: "/api/weekly-schedule-templates",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Tạo mới Mẫu lịch làm việc tuần",
    description: "Thêm một Mẫu lịch làm việc tuần mới vào hệ thống",
    method: "POST",
    path: "/api/weekly-schedule-templates",
    authRequired: true,
    permissions: ["attendance.create"],
  },
  {
    name: "Chi tiết Mẫu lịch làm việc tuần",
    description: "Xem thông tin chi tiết của một Mẫu lịch làm việc tuần",
    method: "GET",
    path: "/api/weekly-schedule-templates/:id",
    authRequired: false,
    permissions: null,
  },
  {
    name: "Cập nhật Mẫu lịch làm việc tuần",
    description: "Chỉnh sửa thông tin Mẫu lịch làm việc tuần hiện có",
    method: "PATCH",
    path: "/api/weekly-schedule-templates/:id",
    authRequired: true,
    permissions: ["attendance.update"],
  },
  {
    name: "Xóa Mẫu lịch làm việc tuần",
    description: "Xóa Mẫu lịch làm việc tuần khỏi hệ thống",
    method: "DELETE",
    path: "/api/weekly-schedule-templates/:id",
    authRequired: true,
    permissions: ["attendance.delete"],
  },
  {
    name: "Thực hiện /:id/apply",
    description: "API endpoint cho Mẫu lịch làm việc tuần",
    method: "POST",
    path: "/api/weekly-schedule-templates/:id/apply",
    authRequired: true,
    permissions: ["attendance.update"],
  },
]
