export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
  },
  HRM: {
    BASE: "/hrm",
    PROFILE: "/hrm/profile",
    EMPLOYEES: "/hrm/employees",
    MY_ACTIVITY_LOGS: "/hrm/my-activity-logs",
    LOGIN_HISTORY: "/hrm/login-history",
    DASHBOARD: "/hrm/dashboard",
    ACTIVITY_LOGS: "/hrm/activity-logs",
  },
  APPLICATION: {
    BASE: "/application",
    DASHBOARD: "/application/dashboard",
    CREATE: "/application/create",
  },
  ATTENDANCE: {
    BASE: "/attendance",
    DASHBOARD: "/attendance/dashboard",
    SUMMARY: "/attendance/summary",
    MY_SCHEDULE: "/attendance/my-schedule",
    WORK_SCHEDULES: "/attendance/work-schedules",
    REAL_SHIFT: "/attendance/real-shift",
    APPLICATIONS: "/attendance/applications",
    SHIFTS: "/attendance/shifts",
    WEEKLY_SCHEDULES: "/attendance/weekly-schedules",
    WEEKLY_SCHEDULE_CONFIG: "/attendance/weekly-schedule-config",
    HOLIDAYS: "/attendance/holidays",
  },
  PAYROLL: {
    BASE: "/payroll",
    LIST: "/payroll/list",
    SALARY_COMPONENTS: "/payroll/salary-components",
    SALARY_VARIABLES: "/payroll/salary-variables",
    PAYSLIP_TEMPLATES: "/payroll/payslip-templates",
    CYCLE: "/payroll/cycle",
    EMPLOYEE_SALARY: "/payroll/employee-salary",
    MY_PAYSLIPS: "/payroll/my-payslips",
  },
  ASSET: {
    BASE: "/asset",
    DASHBOARD: "/asset/dashboard",
  },
  RECRUITMENT: {
    BASE: "/recruitment",
    DASHBOARD: "/recruitment/dashboard",
  },
  SETTINGS: {
    BASE: "/settings",
    DASHBOARD: "/settings/dashboard",
    ROLES: "/settings/roles",
    ROLE_PERMISSIONS: "/settings/role-permissions",
    PERMISSIONS: "/settings/permissions",
  },
  PROJECT: {
    BASE: "/project",
    LIST: "/project/list",
    POSITIONS: "/project/positions",
    DASHBOARD: "/project/dashboard",
    OVERVIEW: "/project/overview",
    ISSUES: "/project/issues",
    TASK_NEW: "/project/task/new",
    TASK_DETAIL: "/project/task",
    DETAIL_TAB: "/project/:tab",
    TASK_NEW_WITH_ID: "/project/:id/task/new",
    TASK_DETAIL_WITH_ID: "/project/task/:id",
  },
  PERSONAL: {
    BASE: "/personal",
    SCHEDULE: "/personal/schedule",
    PAYSLIPS: "/personal/payslips",
    PROJECTS: "/personal/projects",
  },
} as const
