export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
  },
  HRM: {
    BASE: "/hrm",
    PROFILE: "/hrm/profile",
    EMPLOYEES: "/hrm/employees",
    CREATE_EMPLOYEE: "/hrm/employees/create",
    CONTRACTS: "/hrm/contracts",
    CREATE_CONTRACT: "/hrm/contracts/create",
    INSURANCE: "/hrm/insurance",
    MY_ACTIVITY_LOGS: "/hrm/my-activity-logs",
    LOGIN_HISTORY: "/hrm/login-history",
    DASHBOARD: "/hrm/dashboard",
    ACTIVITY_LOGS: "/hrm/activity-logs",
  },
  APPLICATION: {
    BASE: "/application",
    ALL: "/application/all",
    MANAGE: "/application/manage",
    MY_APPLICATIONS: "/application/my-applications",
    CREATE: "/application/create/:type",
  },
  ATTENDANCE: {
    BASE: "/attendance",
    DASHBOARD: "/attendance/dashboard",
    SUMMARY: "/attendance/summary",
    MY_SCHEDULE: "/attendance/my-schedule",
    MY_AVAILABILITY: "/attendance/my-availability",
    WORK_SCHEDULES: "/attendance/work-schedules",
    /** Admin shift assignment from PT employee availability submissions. */
    PART_TIME_AVAILABILITY: "/attendance/part-time-availability",
    REAL_SHIFT: "/attendance/real-shift",
    APPLICATIONS: "/attendance/applications",
    SHIFTS: "/attendance/shifts",
    WEEKLY_SCHEDULES: "/attendance/weekly-schedules",
    WEEKLY_SCHEDULE_CONFIG: "/attendance/weekly-schedule-config",
    HOLIDAYS: "/attendance/holidays",
  },
  PAYROLL: {
    BASE: "/payroll",
    LIST: "/payroll/list",
    SALARY_COMPONENTS: "/payroll/salary-components",
    SALARY_VARIABLES: "/payroll/salary-variables",
    PAYSLIP_TEMPLATES: "/payroll/payslip-templates",
    CYCLE: "/payroll/cycle",
    EMPLOYEE_SALARY: "/payroll/employee-salary",
    MY_PAYSLIPS: "/payroll/my-payslips",
  },
  RECRUITMENT: {
    BASE: "/recruitment",
    DASHBOARD: "/recruitment/dashboard",
    REQUISITIONS: "/recruitment/requisitions",
    REQUISITION_DETAIL: "/recruitment/requisitions/:id",
    REQUISITION_WORKSPACE: "/recruitment/requisitions/:id/:tab",
    JOB_DESCRIPTIONS: "/recruitment/job-descriptions",
    OAUTH_ACCOUNTS: "/recruitment/oauth-accounts",
    APPLICANT_INTAKE: "/recruitment/applicant-intake",
    APPLICATIONS: "/recruitment/applications",
    APPLICATION_DETAIL: "/recruitment/applications/:id",
    MY_INTERVIEWS: "/recruitment/my-interviews",
  },
  SETTINGS: {
    BASE: "/settings",
    ROLES: "/settings/roles",
    ROLE_PERMISSIONS: "/settings/role-permissions",
    PERMISSIONS: "/settings/permissions",
  },
  PROJECT: {
    BASE: "/project",
    LIST: "/project/list",
    MY_PROJECTS: "/project/my-projects",
    POSITIONS: "/project/positions",
    DASHBOARD: "/project/dashboard",
    OVERVIEW: "/project/overview",
    ISSUES: "/project/issues",
    TASK_NEW: "/project/task/new",
    TASK_DETAIL: "/project/task",
    DETAIL_TAB: "/project/:tab",
    TASK_NEW_WITH_ID: "/project/:id/task/new",
    TASK_DETAIL_WITH_ID: "/project/task/:id",
  },
  PERSONAL: {
    BASE: "/attendance/my-schedule",
    SCHEDULE: "/attendance/my-schedule",
    /** Part-time employees submit weekly free-time windows here. */
    AVAILABILITY: "/attendance/my-availability",
    PAYSLIPS: "/payroll/my-payslips",
    PROJECTS: "/project/my-projects",
    APPLICATIONS: "/application/my-applications",
  },
} as const
