// Re-export Prisma generated types for use across the codebase
export type {
  Employee,
  WorkingShift,
  ShiftSchedule,
  EmployeeShift,
  AttendanceRecord,
  Application,
  HolidayCalendar,
  Payroll,
  PayrollComponent,
  PayrollTemplate,
  PayrollTemplateComponent,
  PayrollSettings,
  Payslip,
  PayslipDetail,
  RecruitmentProposal,
  RecruitmentPosting,
  Candidate,
  InterviewSchedule,
  SocialPostLog,
  Project,
  ProjectMember,
  Task,
  ActivityLog,
  PasswordResetRequest,
} from "@prisma/client"
