export const ATTENDANCE_TIME_RULES = {
  DEFAULT_WINDOW_MINUTES: 15,
  MINUTES_PER_DAY: 1440,
  MILLISECONDS_PER_MINUTE: 60000,
} as const

export const ATTENDANCE_GPS_RULES = {
  EARTH_RADIUS_METERS: 6371000,
  DEGREES_TO_RADIANS_DIVISOR: 180,
} as const
