/**
 * Seeds deterministic projects with enough history for Part-time Capacity Copilot demos.
 * Safe to rerun: it deletes only the named demo projects, then recreates demo data.
 */
import { PART_TIME_AVAILABILITY_STATUS } from "@/configs/entities/part-time-availability.config.ts"
import {
  PROJECT_MEMBER_WORK_MODE,
  PROJECT_ROLE,
  PROJECT_STATUS,
  SPENT_TIME_ACTIVITY,
  SPENT_TIME_STATUS,
  SPENT_TIME_WORK_TIME_TYPE,
  TASK_CREATION_POLICY,
  TASK_PRIORITY,
  TASK_STATUS,
  TASK_TRACKER,
} from "@/configs/entities/project.config.ts"
import { prisma } from "@/libs/database.ts"
import { HashUtil } from "@/utils/hash.util.ts"

import { SeedContext, createEmptyContext } from "./seed-context.ts"
import { ISeeder } from "./seeder.interface.ts"
import { registry } from "./seeder.registry.ts"

const DEMO_PROJECT_NAME = "AI Capacity Copilot Demo"
const DEMO_DEAL_TARGET_PERCENT = 50
const SHORTAGE_PROJECT_NAME = "AI Capacity Shortage Demo"
const SHORTAGE_DEAL_TARGET_PERCENT = 30
const DEMO_FORECAST_WEEK_START = new Date("2026-07-27T00:00:00.000Z")
const DEMO_NEXT_FORECAST_WEEK_START = new Date("2026-08-03T00:00:00.000Z")
const DEMO_PREVIOUS_WEEK_START = new Date("2026-07-20T00:00:00.000Z")
const DEMO_PREVIOUS_WEEK_END = new Date("2026-07-26T00:00:00.000Z")
const DEMO_PROJECT_END = new Date("2026-08-31T00:00:00.000Z")
const WORKDAY_START_MINUTES = 8 * 60
const WORKDAY_END_MINUTES = 17 * 60
const MINIMUM_DEMO_EMPLOYEES = 3
const DEMO_DONE_STATUS_NAME = "Done"
const DEMO_WORK_DAYS = [1, 2, 3, 4, 5] as const

const roleSeeds = [
  { code: PROJECT_ROLE.DEVELOPER, name: "Lập trình viên" },
  { code: PROJECT_ROLE.TESTER, name: "Kiểm thử viên" },
  { code: PROJECT_ROLE.LEADER, name: "Trưởng nhóm" },
] as const

const taskStatusSeeds = [
  { name: "To Do", order: 0, isDefault: true, isCompleted: false },
  { name: "In Progress", order: 1, isDefault: false, isCompleted: false },
  { name: DEMO_DONE_STATUS_NAME, order: 2, isDefault: false, isCompleted: true },
] as const

async function pickEmployees(demoTesterId: string) {
  const employees = await prisma.employee.findMany({
    where: { status: "active", deletedAt: null },
    orderBy: { createdAt: "asc" },
  })

  if (employees.length < MINIMUM_DEMO_EMPLOYEES) {
    throw new Error(
      `Cần ít nhất ${MINIMUM_DEMO_EMPLOYEES} nhân viên active để seed demo Capacity Copilot.`,
    )
  }

  const partTimeEmployees = employees.filter(
    (employee) => employee.workScheduleType === "part_time",
  )
  const fullTimeEmployees = employees.filter(
    (employee) => employee.workScheduleType !== "part_time",
  )

  return {
    admin: employees.find((employee) => employee.username === "admin") ?? employees[0],
    developer:
      fullTimeEmployees.find((employee) => employee.position === "Developer") ??
      fullTimeEmployees[0] ??
      employees[1],
    tester:
      partTimeEmployees.find((employee) => employee.id === demoTesterId) ??
      partTimeEmployees.find((employee) => employee.position === "Tester") ??
      partTimeEmployees[0] ??
      employees[2],
  }
}

function addDays(date: Date, days: number): Date {
  const result = new Date(date)
  result.setDate(result.getDate() + days)
  return result
}

export class CapacityDemoSeeder implements ISeeder {
  readonly name = "CapacityDemo"
  readonly order = 22

  async run(context: SeedContext): Promise<Partial<SeedContext>> {
    // Relying on core accounts generated by 01-employees.seeder.ts
    const demoTester =
      context.employees.find((e) => e.username === "part_time") ??
      (await prisma.employee.findFirst({ where: { username: "part_time" } }))
    if (!demoTester) {
      console.warn("CapacityCopilot: part_time user not found. Skipping demo seed.")
      return {}
    }
    const people = await pickEmployees(demoTester.id)

    await prisma.project.deleteMany({
      where: { name: { in: [DEMO_PROJECT_NAME, SHORTAGE_PROJECT_NAME] } },
    })

    const project = await prisma.project.create({
      data: {
        name: DEMO_PROJECT_NAME,
        description: "Demo project đầy đủ dữ kiện cho Part-time Capacity Copilot.",
        techStack: ["React", "Node.js", "PostgreSQL"],
        status: PROJECT_STATUS.ACTIVE,
        taskCreationPolicy: TASK_CREATION_POLICY.ALL_MEMBERS,
        startDate: addDays(DEMO_PREVIOUS_WEEK_START, -21),
        expectedEndDate: DEMO_PROJECT_END,
        dealTargetPercent: DEMO_DEAL_TARGET_PERCENT,
        teamLeaderId: people.admin.id,
        createdById: people.admin.id,
        allowedTaskTrackers: [TASK_TRACKER.FEATURE, TASK_TRACKER.TEST, TASK_TRACKER.TASK],
      },
    })

    const roles = await Promise.all(
      roleSeeds.map((role) =>
        prisma.projectRole.create({
          data: {
            projectId: project.id,
            code: role.code,
            name: role.name,
          },
        }),
      ),
    )
    const roleByCode = new Map(roles.map((role) => [role.code, role]))

    const statuses = await Promise.all(
      taskStatusSeeds.map((status) =>
        prisma.projectTaskStatus.create({
          data: {
            projectId: project.id,
            name: status.name,
            order: status.order,
            isDefault: status.isDefault,
            isCompleted: status.isCompleted,
          },
        }),
      ),
    )
    const doneStatus = statuses.find((status) => status.name === DEMO_DONE_STATUS_NAME)

    await prisma.projectMember.createMany({
      data: [
        {
          projectId: project.id,
          employeeId: people.admin.id,
          roleId: roleByCode.get(PROJECT_ROLE.LEADER)?.id,
          workMode: PROJECT_MEMBER_WORK_MODE.REMOTE,
        },
        {
          projectId: project.id,
          employeeId: people.developer.id,
          roleId: roleByCode.get(PROJECT_ROLE.DEVELOPER)?.id,
          workMode: PROJECT_MEMBER_WORK_MODE.REMOTE,
          hourlyRate: 50000,
        },
        {
          projectId: project.id,
          employeeId: people.tester.id,
          roleId: roleByCode.get(PROJECT_ROLE.TESTER)?.id,
          workMode: PROJECT_MEMBER_WORK_MODE.REMOTE,
          hourlyRate: 50000,
        },
      ],
      skipDuplicates: true,
    })

    const historyWeeks = [
      {
        start: addDays(DEMO_PREVIOUS_WEEK_START, -14),
        completedAt: addDays(DEMO_PREVIOUS_WEEK_START, -10),
        title: "Hoàn thành module nhập lịch rảnh",
      },
      {
        start: addDays(DEMO_PREVIOUS_WEEK_START, -7),
        completedAt: addDays(DEMO_PREVIOUS_WEEK_START, -3),
        title: "Hoàn thành dashboard capacity",
      },
      {
        start: DEMO_PREVIOUS_WEEK_START,
        completedAt: addDays(DEMO_PREVIOUS_WEEK_START, 3),
        title: "Hoàn thành rule cảnh báo thiếu capacity",
      },
    ]

    const doneTasks = await Promise.all(
      historyWeeks.flatMap((week, index) => [
        prisma.task.create({
          data: {
            projectId: project.id,
            title: `${week.title} - backend ${index + 1}`,
            tracker: TASK_TRACKER.FEATURE,
            priority: TASK_PRIORITY.HIGH,
            status: TASK_STATUS.DONE,
            statusId: doneStatus?.id,
            assigneeId: people.developer.id,
            createdById: people.admin.id,
            startDate: week.start,
            dueDate: addDays(week.start, 6),
            completedAt: week.completedAt,
            estimatedTime: 12,
            progress: 100,
          },
        }),
        prisma.task.create({
          data: {
            projectId: project.id,
            title: `${week.title} - testing ${index + 1}`,
            tracker: TASK_TRACKER.TEST,
            priority: TASK_PRIORITY.MEDIUM,
            status: TASK_STATUS.DONE,
            statusId: doneStatus?.id,
            assigneeId: people.tester.id,
            createdById: people.admin.id,
            startDate: week.start,
            dueDate: addDays(week.start, 6),
            completedAt: addDays(week.completedAt, 1),
            estimatedTime: 8,
            progress: 100,
          },
        }),
      ]),
    )

    await prisma.task.create({
      data: {
        projectId: project.id,
        title: "Implement module forecast tuần được chọn",
        tracker: TASK_TRACKER.FEATURE,
        priority: TASK_PRIORITY.HIGH,
        status: TASK_STATUS.IN_PROGRESS,
        assigneeId: people.developer.id,
        createdById: people.admin.id,
        startDate: DEMO_FORECAST_WEEK_START,
        dueDate: addDays(DEMO_FORECAST_WEEK_START, 6),
        estimatedTime: 30,
        progress: 30,
      },
    })

    await prisma.spentTime.createMany({
      data: doneTasks.map((task, index) => {
        const isDeveloperTask = index % 2 === 0
        return {
          taskId: task.id,
          employeeId: isDeveloperTask ? people.developer.id : people.tester.id,
          date: addDays(addDays(DEMO_PREVIOUS_WEEK_START, -14), index * 3),
          hours: isDeveloperTask ? 12 : 8,
          comment: "Demo history: approved spent time for Capacity Copilot.",
          activity: isDeveloperTask ? SPENT_TIME_ACTIVITY.DEVELOP : SPENT_TIME_ACTIVITY.TEST,
          workTimeType: SPENT_TIME_WORK_TIME_TYPE.WORKING_DAY,
          status: SPENT_TIME_STATUS.APPROVED,
          approvedById: people.admin.id,
          approvedAt: addDays(DEMO_PREVIOUS_WEEK_START, 4),
        }
      }),
    })

    // Seed both currently demoed weeks so the board and project detail page do not show
    // 0h capacity merely because the reviewer opened the following week.
    await Promise.all(
      [DEMO_FORECAST_WEEK_START, DEMO_NEXT_FORECAST_WEEK_START].map((weekStart) =>
        prisma.partTimeWeeklyAvailability.upsert({
          where: {
            employeeId_weekStart: {
              employeeId: people.tester.id,
              weekStart,
            },
          },
          update: {},
          create: {
            employeeId: people.tester.id,
            weekStart,
            status: PART_TIME_AVAILABILITY_STATUS.SUBMITTED,
            submittedAt: new Date("2026-07-19T08:00:00.000Z"),
            note: "Demo availability for Capacity Copilot.",
            days: {
              create: DEMO_WORK_DAYS.map((dayOfWeek) => ({
                dayOfWeek,
                isBusyAllDay: false,
                slots: {
                  create: {
                    startTime: WORKDAY_START_MINUTES,
                    endTime: WORKDAY_END_MINUTES,
                    sortOrder: 0,
                  },
                },
              })),
            },
          },
        }),
      ),
    )

    // This second project is intentionally under-capacity: target is realistic (30%),
    // predicted is lower, and needed hours stay readable for side-by-side comparison.
    const shortageProject = await prisma.project.create({
      data: {
        name: SHORTAGE_PROJECT_NAME,
        description: "Demo project cố tình thiếu capacity để so sánh trên Capacity Board.",
        techStack: ["React", "Node.js", "PostgreSQL"],
        status: PROJECT_STATUS.ACTIVE,
        taskCreationPolicy: TASK_CREATION_POLICY.ALL_MEMBERS,
        startDate: addDays(DEMO_PREVIOUS_WEEK_START, -21),
        expectedEndDate: DEMO_PROJECT_END,
        dealTargetPercent: SHORTAGE_DEAL_TARGET_PERCENT,
        teamLeaderId: people.admin.id,
        createdById: people.admin.id,
        allowedTaskTrackers: [TASK_TRACKER.FEATURE, TASK_TRACKER.TEST, TASK_TRACKER.TASK],
      },
    })

    const shortageRoles = await Promise.all(
      roleSeeds.map((role) =>
        prisma.projectRole.create({
          data: {
            projectId: shortageProject.id,
            code: role.code,
            name: role.name,
          },
        }),
      ),
    )
    const shortageRoleByCode = new Map(shortageRoles.map((role) => [role.code, role]))

    const shortageStatuses = await Promise.all(
      taskStatusSeeds.map((status) =>
        prisma.projectTaskStatus.create({
          data: {
            projectId: shortageProject.id,
            name: status.name,
            order: status.order,
            isDefault: status.isDefault,
            isCompleted: status.isCompleted,
          },
        }),
      ),
    )
    const shortageDoneStatus = shortageStatuses.find(
      (status) => status.name === DEMO_DONE_STATUS_NAME,
    )

    await prisma.projectMember.create({
      data: {
        projectId: shortageProject.id,
        employeeId: people.tester.id,
        roleId: shortageRoleByCode.get(PROJECT_ROLE.TESTER)?.id,
        workMode: PROJECT_MEMBER_WORK_MODE.REMOTE,
        hourlyRate: 50000,
      },
    })

    const shortageHistoryWeeks = [
      {
        start: addDays(DEMO_PREVIOUS_WEEK_START, -14),
        completedAt: addDays(DEMO_PREVIOUS_WEEK_START, -11),
        title: "Fix luồng kiểm thử đăng nhập",
      },
      {
        start: addDays(DEMO_PREVIOUS_WEEK_START, -7),
        completedAt: addDays(DEMO_PREVIOUS_WEEK_START, -4),
        title: "Kiểm thử regression dashboard",
      },
      {
        start: DEMO_PREVIOUS_WEEK_START,
        completedAt: addDays(DEMO_PREVIOUS_WEEK_START, 3),
        title: "Kiểm thử báo cáo capacity",
      },
    ]

    const shortageDoneTasks = await Promise.all(
      shortageHistoryWeeks.map((week, index) =>
        prisma.task.create({
          data: {
            projectId: shortageProject.id,
            title: `${week.title} ${index + 1}`,
            tracker: TASK_TRACKER.TEST,
            priority: TASK_PRIORITY.MEDIUM,
            status: TASK_STATUS.DONE,
            statusId: shortageDoneStatus?.id,
            assigneeId: people.tester.id,
            createdById: people.admin.id,
            startDate: week.start,
            dueDate: addDays(week.start, 6),
            completedAt: week.completedAt,
            estimatedTime: 20,
            progress: 100,
          },
        }),
      ),
    )

    await prisma.task.createMany({
      data: [
        {
          projectId: shortageProject.id,
          title: "Backlog lớn: refactor module báo cáo",
          tracker: TASK_TRACKER.FEATURE,
          priority: TASK_PRIORITY.HIGH,
          status: TASK_STATUS.IN_PROGRESS,
          assigneeId: people.tester.id,
          createdById: people.admin.id,
          startDate: DEMO_FORECAST_WEEK_START,
          dueDate: addDays(DEMO_FORECAST_WEEK_START, 6),
          estimatedTime: 80,
          progress: 15,
        },
        {
          projectId: shortageProject.id,
          title: "Backlog lớn: kiểm thử nghiệp vụ payroll",
          tracker: TASK_TRACKER.TEST,
          priority: TASK_PRIORITY.HIGH,
          status: TASK_STATUS.TODO,
          assigneeId: people.tester.id,
          createdById: people.admin.id,
          startDate: DEMO_FORECAST_WEEK_START,
          dueDate: addDays(DEMO_FORECAST_WEEK_START, 6),
          estimatedTime: 60,
          progress: 0,
        },
        {
          projectId: shortageProject.id,
          title: "Backlog lớn: hardening phân quyền",
          tracker: TASK_TRACKER.TASK,
          priority: TASK_PRIORITY.HIGH,
          status: TASK_STATUS.TODO,
          assigneeId: people.tester.id,
          createdById: people.admin.id,
          startDate: DEMO_FORECAST_WEEK_START,
          dueDate: addDays(DEMO_FORECAST_WEEK_START, 6),
          estimatedTime: 40,
          progress: 0,
        },
      ],
    })

    await prisma.spentTime.createMany({
      data: shortageDoneTasks.map((task, index) => ({
        taskId: task.id,
        employeeId: people.tester.id,
        date: addDays(addDays(DEMO_PREVIOUS_WEEK_START, -14), index * 7 + 2),
        hours: 20,
        comment: "Demo shortage: nhiều giờ log nhưng hoàn thành ít % scope.",
        activity: SPENT_TIME_ACTIVITY.TEST,
        workTimeType: SPENT_TIME_WORK_TIME_TYPE.WORKING_DAY,
        status: SPENT_TIME_STATUS.APPROVED,
        approvedById: people.admin.id,
        approvedAt: addDays(DEMO_PREVIOUS_WEEK_START, 4),
      })),
    })

    console.log("Seeded Capacity Copilot demo projects.")
    console.log(`Project: ${project.name}`)
    console.log(`Target: ${DEMO_DEAL_TARGET_PERCENT}%`)
    console.log(`Shortage project: ${shortageProject.name}`)
    console.log(`Shortage target: ${SHORTAGE_DEAL_TARGET_PERCENT}%`)
    console.log("Forecast weeks: 27/07/2026 - 02/08/2026 and 03/08/2026 - 09/08/2026")
    console.log("History: 3 previous weeks with approved spent time and done tasks.")
    console.log(
      "Demo tip: shortage project uses a fixed 30% deal target for a realistic comparison.",
    )

    return {}
  }
}

registry.register(new CapacityDemoSeeder())

if (import.meta.main) {
  const seeder = new CapacityDemoSeeder()
  await seeder.run(createEmptyContext())
  await prisma.$disconnect()
}
