// Auto-register seeders (import them here as they are created)
import "./01-employees.seeder.ts"
import "./02-working-shifts.seeder.ts"
import "./03-holiday-calendars.seeder.ts"
import "./04-shift-schedules.seeder.ts"
import "./05-salary-components.seeder.ts"
import "./05b-salary-variables.seeder.ts"
import "./06-payslip-templates.seeder.ts"
import "./07-payroll-settings.seeder.ts"
import "./08-projects.seeder.ts"
import "./08b-project-task-statuses.seeder.ts"
import "./09-employee-shifts.seeder.ts"
import "./10-salary-configs.seeder.ts"
import "./11-project-members.seeder.ts"
import "./12-attendance-records.seeder.ts"
import "./13-applications.seeder.ts"
import "./14-payrolls.seeder.ts"
import "./15-tasks.seeder.ts"
import "./16-payslips.seeder.ts"
import "./17-activity-logs.seeder.ts"
import "./18-spent-times.seeder.ts"

export { registry } from "./seeder.registry.ts"
export type { ISeeder } from "./seeder.interface.ts"
export type { SeedContext } from "./seed-context.ts"
export { createEmptyContext } from "./seed-context.ts"
